services:
  db:
    image: postgres:16
    container_name: odinpos-db
    environment:
      POSTGRES_USER: odin
      POSTGRES_PASSWORD: odin123
      POSTGRES_DB: odinpos
    ports:
      - "5432:5432"
    volumes:
      - odinpos_pg:/var/lib/postgresql/data

volumes:
  odinpos_pg:

